### ISSUE TITLE
Libredirect for twitter can't use nitter.net or any custom instance.

### ISSUE THREAD

**Issue by Kezxo** [1fexd/LinkSheet#167]
### Bug description

The libredirect feature for twitter has a set list of instances but `nitter.net` isn't there and there is seemingly no way to enter a custom instance. That last bit must be an oversight right? Custom instances should be a given?

PS: When I tried nightly just opening the libredirect page just gives me a crash log, ill post that log below but i suspects its a different issue.. All I did was install it, go to settings and open the libredirect menu.

So I set the "reproducable on nightly" to yes since its technically true..

### Version

0.0.33

### Device

OnePlus 8T

### Android version

OxygenOS 13 (based on Android 13)

### Application log or crash log

This log didn't happen on 0.0.33, it was on latest nightly but figured ill include it.

```
java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
	at q5.a.<init>(SourceFile:3)
	at d6.a.u1(SourceFile:27)
	at d6.a.t1(SourceFile:12)
	at fe.linksheet.module.viewmodel.LibRedirectSettingsViewModel$special$$inlined$flowOfLazy$1.j(SourceFile:1)
	at fe.linksheet.module.viewmodel.LibRedirectSettingsViewModel$special$$inlined$flowOfLazy$1.K(SourceFile:13)
	at m4.n.d(SourceFile:109)
	at v9.r.j(SourceFile:43)
	at v6.a.h(SourceFile:1)
	at s9.f0.run(SourceFile:1)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
		at q5.a.<init>(SourceFile:3)
		at d6.a.u1(SourceFile:27)
		at d6.a.s1(SourceFile:12)
		at fe.linksheet.module.viewmodel.LibRedirectSettingsViewModel$special$$inlined$flowOfLazy$2.j(SourceFile:1)
		at fe.linksheet.module.viewmodel.LibRedirectSettingsViewModel$special$$inlined$flowOfLazy$2.K(SourceFile:13)
		... 7 more
	Suppressed: r8.m0: [androidx.compose.ui.platform.s1@391cb78, l0.f@7e26251, q1{Cancelling}@febab6, s0@81d23b7]


linksheet_version=master-9e8dfdd-nightly,code=1692342853
device_fingerprint=OnePlus/OnePlus8T_EEA/OnePlus8T:13/RKQ1.211119.001/R.113a31b-6826-6827:user/release-keys
preferences:
enable_copy_button=false
hide_after_copying=false
single_tap=false
usage_stats_sorting=false
browser_mode=null
in_app_browser_mode=null
unified_preferred_browser=true
in_app_browser_setting=null
enable_send_button=false
always_show_package_name=false
disable_toasts=false
grid_layout=false
use_clear_urls=false
fast_forward_rules=false
enable_lib_redirect=true
follow_redirects=false
follow_redirects=false
follow_redirects_local_cache=true
follow_redirects_external_service=false
follow_only_known_trackers=false
theme=null
dont_show_filtered_item=false
use_text_share_copy_buttons=false
preview_url=false
enable_downloader=false
downloaderCheckUrlMimeType=false
enable_ignore_lib_redirect_button=false
follow_redirects_timeout=15
enable_request_private_browsing_button=false
enable_amp2html=false
amp2html_local_cache=true
amp2html_external_service=false
follow_redirects_builtin_cache=true
amp2html_builtin_cache=true
feature_flag_shizuku=false
first_run=true
selected_browsernull
selected_in_app_browsernull
```

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
> That last bit must be an oversight right?

No, that's the intended behavior. The current implementation only allows to select the upstream domains.

> Custom instances should be a given?

No one ever asked 😆 but I can look into it.

**Comment by Kezxo** [comment]
> No, that's the intended behavior. The current implementation only allows to select the upstream domains.

I just expected that the official nitter domain would be there and did a lot of scrolling to learn that it wasn't the case.

> Hm, maybe a domain you previously selected is not available anymore and LinkSheet doesn't know how to handle that. I'll check.

I doubt it, I had never used nightly before so it was a totally fresh install.

> No one ever asked 😆 but I can look into it.

Thanks! 👍

**Comment by 1fexd** [comment]
> I just expected that the official nitter domain would be there and did a lot of scrolling to learn that it wasn't the case.

Strange, I am using LibRedirect's domains, so this must be an issue on their end

> I doubt it, I had never used nightly before so it was a totally fresh install.

Will look into it.

**Comment by 1fexd** [comment]
Hello, this has been stale for a while - are you still using the app / LibRedirect? If so, does it work better now (on the latest nightly)? I know there is still no support for custom instances - just trying to figure out how to prioritize this.

**Comment by PhilC813** [comment]
The nitter.net domain is officially back from the dead (see the [post from the dev](https://github.com/zedeus/nitter/discussions/1212#discussion-7921789)) but it's still not available in the LibRedirect section of LinkSheet.

Is there any update on this? Having a way to override by entering a custom domain would prove useful in situations like this.

Thank you!!

**Comment by 1fexd** [comment]
The experiment `Custom instances` under `LibRedirect`, which addresses this issue, has been available for quite some time, not sure if you've noticed.
