### ISSUE TITLE
Crash when exporting

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheet#337]
### Bug description

Using the latest nightly, LinkSheet crashes when exporting settings with the following message: 

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=307953841, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/... flg=0x43 }} to activity {fe.linksheet.nightly/fe.linksheet.activity.MainActivity}: java.lang.ClassCastException: h8.e$c cannot be cast to h8.e$g
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6062)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.ClassCastException: h8.e$c cannot be cast to h8.e$g
	at fe.linksheet.module.preference.AppPreferenceRepository.r(SourceFile:195)
	at fe.linksheet.composable.settings.advanced.exportimport.ExportSettingsDialogKt$ExportSettingsDialog$fileSelectedLauncher$1.m(SourceFile:58)
	at f0.b.b(SourceFile:11)
	at h0.c.a(SourceFile:49)
	at e0.i.onActivityResult(SourceFile:1)
	at android.app.Activity.dispatchActivityResult(Activity.java:9340)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6055)
	... 13 more
```

A 0 byte file is created with the correct file name.

### Version

LinkSheet Version Information: Built at (UTC): 2024-03-07 14:05:57 Flavor: Foss Type: nightly Commit: 9f65588 Branch: master Full identifier: master-9f65588-nightly Build workflow ID: 8194121941

### Device

Fold5

### Android version

Android 14 (One UI 6)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Could you please confirm the fix works?
